# -*- coding: utf-8 -*-
"""
gvl.py - GVL (Global Variable List) generation for CODESYS.

This module detects runtime variable references in SVG-derived element specs
and generates a ``.st`` GVL file with the required declarations.  It is called
from ``commands.from_svg`` when ``--gvl`` or ``--gvl-file`` is used.

Usage::

    from cli.visu import gvl

    vars = gvl.collect_variables(elements)
    st = gvl.generate_gvl(vars, gvl_name="VisuVars")
    gvl.write_gvl_file("path/to/VisuVars.st", st)
"""

from __future__ import print_function

import os
import re

# ---------------------------------------------------------------------------
# Variable detection
# ---------------------------------------------------------------------------

_DOTTED_VAR_RE = re.compile(r"[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)+")


def collect_variables(elements):
    """Scan a list of ElementSpec dicts for runtime variable references.

    Checks these sources:

    - ``params["text_var"]`` (``data-text-var``)
    - ``params["tap_var"]`` (``data-cds-tap`` with ``st:`` prefix)
    - ``params["toggle_var"]`` (``data-cds-tap`` with ``toggle:`` prefix)
    - ``params["configured_inputs"][*]["values"]["variable"]``
    - ``params["input_actions"][*]["values"]`` keys like ``variable``,
      ``snippet`` (ST snippet content is scanned for dotted variables).

    Returns a deduplicated dict mapping *variable path* → *variable name*
    (the last segment of the dotted path).  Example::

        {"HMI.Temperature": "Temperature", "HMI.PumpRunning": "PumpRunning"}
    """
    variables = {}  # full_path -> short_name

    for elem in elements:
        params = elem.get("params", {})

        # data-text-var
        text_var = params.get("text_var")
        if text_var:
            _record_var(text_var, variables)

        # data-cds-tap / data-cds-action: tap_var
        tap_var = params.get("tap_var")
        if tap_var:
            _record_var(tap_var, variables)

        # toggle_var
        toggle_var = params.get("toggle_var")
        if toggle_var:
            _record_var(toggle_var, variables)

        # configured_complex_inputs (used by the new action parser)
        for action in params.get("configured_inputs", []):
            vals = action.get("values", {})
            for key in ("variable",):
                v = vals.get(key)
                if v:
                    _record_var(v, variables)
            # ST snippet content may contain variable references.
            snippet = vals.get("snippet", "")
            if snippet:
                for m in _DOTTED_VAR_RE.finditer(snippet):
                    _record_var(m.group(), variables)

        # input_actions (used by the old action parser)
        for action in params.get("input_actions", []):
            vals = action.get("values", {})
            for key in ("variable",):
                v = vals.get(key)
                if v:
                    _record_var(v, variables)
            snippet = vals.get("snippet", "")
            if snippet:
                for m in _DOTTED_VAR_RE.finditer(snippet):
                    _record_var(m.group(), variables)

    return variables


def _record_var(var_expr, variables):
    """Parse a variable expression and record it in the *variables* dict.

    Handles dotted paths (``HMI.Temperature``) and bare names.
    Skips ST keyword expressions.
    """
    expr = var_expr.strip()
    # If it looks like a dotted variable path, extract it.
    if "." in expr:
        parts = expr.split(".")
        # Take the full dotted path as the key.
        variables[expr] = parts[-1]
    elif re.match(r"^[A-Za-z_]\w*$", expr):
        # Bare name (no GVL prefix).
        variables[expr] = expr


# ---------------------------------------------------------------------------
# ST generation
# ---------------------------------------------------------------------------

_HEADER = """\
{attribute 'qualified_only'}
VAR_GLOBAL
"""

_FOOTER = """\
END_VAR
"""

_VAR_DECL = """\
    {name} : {type};
"""

_HIDED_ATTR = """\
    {attribute 'hide'}
"""


def generate_gvl(variables, gvl_name="VisuVars", default_type="BOOL"):
    """Generate a GVL ``.st`` file as a string.

    *variables*: dict of ``{full_path: short_name}`` (from ``collect_variables``).
    *gvl_name*: name of the GVL (used in file header, e.g. ``GVL_VisuVars``).
    *default_type*: ST type to use when none can be inferred (default ``BOOL``).

    Returns the full ``.st`` file text.
    """
    if not variables:
        return ""

    lines = []
    lines.append(_HEADER)
    lines.append(_HIDED_ATTR)
    lines.append("    // Auto-generated by cts visu from-svg --gvl\n")

    # Sort for deterministic output.
    for full_path in sorted(variables, key=lambda s: s.lower()):
        short_name = variables[full_path]
        if "." in full_path:
            # For dotted paths like HMI.Temperature, we declare the short name.
            # The 'qualified_only' attribute ensures the GVL prefix is used.
            lines.append(
                "    {name} : {type};\n".format(name=short_name, type=default_type)
            )
        else:
            lines.append(
                "    {name} : {type};\n".format(name=full_path, type=default_type)
            )

    lines.append(_FOOTER)
    return "".join(lines)


def write_gvl_file(path, content):
    """Write *content* to *path*, creating parent directories as needed."""
    if not content:
        return
    directory = os.path.dirname(path)
    if directory and not os.path.isdir(directory):
        os.makedirs(directory)
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)


# ---------------------------------------------------------------------------
# Existing GVL scanning (deduplication)
# ---------------------------------------------------------------------------


def detect_existing_variables(gvl_path):
    """Scan an existing GVL ``.st`` file for declared variable names.

    Returns a set of variable names (the last segment after ``.`` if dotted).
    """
    if not os.path.isfile(gvl_path):
        return set()
    existing = set()
    var_decl_re = re.compile(r"^\s+(\w+)\s*:")
    with open(gvl_path, "r", encoding="utf-8") as handle:
        for line in handle:
            m = var_decl_re.match(line)
            if m:
                existing.add(m.group(1))
    return existing


# ---------------------------------------------------------------------------
# High-level API
# ---------------------------------------------------------------------------


def ensure_gvl(project_view_dir, elements, gvl_name="VisuVars", gvl_path=None):
    """Ensure a GVL file exists for the variables referenced by *elements*.

    Returns the path to the GVL file that was written, or ``None`` if no
    variables were detected.

    *project_view_dir*: root of the project-view (used for default path).
    *elements*: list of ElementSpec dicts.
    *gvl_name*: GVL name (default ``VisuVars``).
    *gvl_path*: explicit output path (default
        ``<project_view_dir>/POUs/<gvl_name>.st``).
    """
    variables = collect_variables(elements)
    if not variables:
        return None

    if not gvl_path:
        gvl_dir = os.path.join(project_view_dir, "POUs")
        gvl_path = os.path.join(gvl_dir, gvl_name + ".st")

    # Check for duplicates against existing file.
    existing = detect_existing_variables(gvl_path)
    new_vars = {k: v for k, v in variables.items() if v not in existing}

    if not new_vars:
        # All variables already declared.
        return gvl_path

    content = generate_gvl(new_vars, gvl_name=gvl_name)

    if os.path.isfile(gvl_path):
        # Append to existing GVL (insert new declarations before END_VAR).
        with open(gvl_path, "r", encoding="utf-8") as handle:
            existing_text = handle.read()
        end_marker = "END_VAR"
        idx = existing_text.rfind(end_marker)
        if idx >= 0:
            # Extract the variable declarations (skip header/footer).
            new_block = content[len(_HEADER) : -len(_FOOTER)]
            content = existing_text[:idx] + new_block + existing_text[idx:]
        else:
            content = existing_text + "\n" + content

    write_gvl_file(gvl_path, content)
    return gvl_path
