# -*- coding: utf-8 -*-
"""Check the bridge's CODESYS scripting-API calls against a committed snapshot.

The bridge talks to CODESYS through the objects the script engine provides --
``system``, ``online``, ``projects``, an online application (``oa``), devices and
script objects.  Those are .NET objects: a wrong member name is an
``AttributeError`` at run time, on the live stand, in the middle of a daemon
command.  ``cts read-log`` was such a bug.

``products/codesys-host/api/scriptengine_api.json`` holds the member names and
declarations of that API (generated by ``tools/script_api_snapshot.py``).  This
tool walks the bridge's AST, finds ``<receiver>.<member>`` uses for the receivers
it knows how to type, and fails when a member is not in the snapshot.

Receivers are matched by *variable name*, so the map below is deliberately small:
only names that mean one thing in this codebase.  Guessing at ``app``/``device``
would produce noise, and a checker that cries wolf is worse than none.

Usage::

    python tools/check_script_api.py             # report
    python tools/check_script_api.py --ci        # exit 1 on an unreviewed finding
"""

from __future__ import print_function

import argparse
import ast
import json
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
_SNAPSHOT = os.path.join(
    _ROOT, "products", "codesys-host", "api", "scriptengine_api.json"
)
_BRIDGE = os.path.join(_ROOT, "products", "codesys-host", "src", "ide_bridge")

#: receiver variable -> scripting-API families it can hold.  Keep this honest:
#: every entry is a name that has exactly one meaning in ``ide_bridge``.
RECEIVERS = {
    "system": ("ISystem",),
    "online": ("IScriptOnline",),
    "projects": ("IScriptProjects",),
    "oa": ("IScriptOnlineApplication",),
    "device": ("IScriptDeviceObject", "IScriptTreeObject"),
    "app": ("IScriptApplication", "IScriptObject"),
}

#: Members every .NET object has; the bridge uses GetType() for reflection and
#: GetHashCode() for identity caches, and neither belongs to the scripting API.
OBJECT_MEMBERS = frozenset(
    ["GetType", "GetHashCode", "ToString", "Equals", "MemberwiseClone", "ReferenceEquals"]
)

#: Calls this tool knows are not in the API, with the reason they are still there.
#: Every entry is a bug the snapshot caught; fixing one means deleting its line.
#: Empty on purpose: ``projects.close(prj)`` was the one entry, and the product
#: fix replaced it (IScriptProject has close(), IScriptProjects does not).
KNOWN_MISMATCHES = {}


def _variants(member):
    """Names under which CODESYS exposes a member of the scripting API.

    Python sees ``get_simulation_mode``/``set_simulation_mode`` (the interface
    spells them out) but the bridge writes ``is_simulation_mode``; accept both.
    """
    names = {member}
    for prefix in ("get_", "set_", "is_"):
        if member.startswith(prefix):
            names.add(member[len(prefix):])
    if member.startswith("is_"):
        names.add("get_" + member[3:])
    return names


def load_snapshot(path=_SNAPSHOT):
    with open(path, "r", encoding="utf-8") as handle:
        snapshot = json.load(handle)
    families = {}
    for family, data in snapshot.get("families", {}).items():
        families[family] = set(data.get("members", {}))
    return families


def _bridge_files(paths):
    if paths:
        return [os.path.abspath(p) for p in paths]
    return sorted(
        os.path.join(_BRIDGE, name)
        for name in os.listdir(_BRIDGE)
        if name.endswith(".py")
    )


def find_calls(paths=None):
    """Yield ``(file, line, receiver, member, variants)`` for known receivers."""
    for path in _bridge_files(paths):
        with open(path, "r", encoding="utf-8", errors="replace") as handle:
            source = handle.read()
        try:
            tree = ast.parse(source, filename=path)
        except SyntaxError:
            continue
        for node in ast.walk(tree):
            if not isinstance(node, ast.Attribute):
                continue
            value = node.value
            if not isinstance(value, ast.Name) or value.id not in RECEIVERS:
                continue
            yield path, node.lineno, value.id, node.attr, _variants(node.attr)


def check(paths=None, snapshot_path=_SNAPSHOT):
    """Return the list of uses that are neither in the API nor a known mismatch."""
    families = load_snapshot(snapshot_path)
    findings = []
    for path, line, receiver, member, variants in find_calls(paths):
        if member in OBJECT_MEMBERS:
            continue
        known = set()
        for family in RECEIVERS[receiver]:
            known |= families.get(family, set())
        if known & variants:
            continue
        if (receiver, member) in KNOWN_MISMATCHES:
            continue
        findings.append((os.path.relpath(path, _ROOT), line, receiver, member))
    return findings


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("paths", nargs="*", help="files to check (default: the bridge)")
    parser.add_argument("--ci", action="store_true", help="exit 1 on any finding")
    args = parser.parse_args(argv)

    findings = check(args.paths)
    for path, line, receiver, member in findings:
        print("{0}:{1}: {2}.{3} is not in the scripting API snapshot".format(
            path, line, receiver, member
        ))
    if not findings:
        print("script API check: all known receiver calls exist in the snapshot")
    if args.ci and findings:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
